using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ReplayParser.Entities
{
    public enum EngineType
    { 
        Starcraft = 0x00,
        Broodwar = 0x01
    }

    public enum GameType
    { 
        Melee = 0x02,
        // 0x03 is MISSING!! == OneOnOne??? No, FreeForAll, it seems FreeForAll was wrong... and 0x04 == OneOnOne
        FreeForAll = 0x03,
        OneOnOne = 0x04,
        CaptureTheFlag = 0x05,
        Greed = 0x06,
        Slaughter = 0x07,
        SuddenDeath = 0x08,
        Ladder = 0x09,
        UseMapSettings = 0x0a,
        TeamMelee = 0x0b,
        TeamFreeForAll = 0x0c,
        TeamCaptureTheFlag = 0x0d,
        TopVsBottom = 0x0f,
        Unknown = 0x10
    }

    public enum ColourType
    { 
        Unknown = 0xFF,
        Red = 0x00,
        Blue = 0x01,
        Purple = 0x02,
        Orange = 0x03,
        Brown = 0x04,
        White = 0x05,
        Yellow = 0x06,
        Green = 0x07
    }

    public enum RaceType
    {
        Zerg = 0x00,
        Terran = 0x01,
        Protoss = 0x02,
        Other = 0x03,
        Select = 0x05,
        Random = 0x06,
        None = 0x07
    }

    public enum SlotType
    { 
        None = 0xFF,
        Slot_0 = 0x00,
        Slot_1 = 0x01,
        Slot_2 = 0x02,
        Slot_3 = 0x03,
        Slot_4 = 0x04,
        Slot_5 = 0x05,
        Slot_6 = 0x06,
        Slot_7 = 0x07,
        Slot_8 = 0x08
    }

    public enum PlayerType
    {

        None = 0x00,
        Computer = 0x01,
        Human = 0x02
    }

    public enum ActionType
    { 
        LegacyGameChat = 0x00,
        ClaimHost = 0x01,
        KeepAlive = 0x05,

        SaveGame = 0x06,
        LoadGame = 0x07,
        RestartGame = 0x08,

        Select = 0x09,
        ShiftSelect = 0x0a,
        ShiftDeselect = 0x0b,

        Build = 0x0c,
        Vision = 0x0d,
        Ally = 0x0e,

        ChangeGameSpeed = 0x0f,
        PauseGame = 0x10,
        ResumeGame = 0x11,

        UseCheat = 0x12,
        HotKey = 0x13,
        RightClick = 0x14,
        Target = 0x15,

        CancelConstruction = 0x18,
        CancelUnitMorph = 0x19,

        Stop = 0x1a,
        CarrierStop = 0x1b,
        ReaverStop = 0x1c,
        ReturnCargo = 0x1e,

        Train = 0x1f,
        CancelTrain = 0x20,

        Cloak = 0x21,
        Decloak = 0x22,

        UnitMorph = 0x23,
        Unsiege = 0x25,
        Siege = 0x26,
        BuildSubunit = 0x27,
        UnloadAll = 0x28,
        Unload = 0x29,
        MergeArchon = 0x2a,
        HoldPosition = 0x2b,

        Burrow = 0x2c,
        Unburrow = 0x2d,

        CancelNuke = 0x2e,
        Lift = 0x2f,
        Research = 0x30,
        CancelResearch = 0x31,
        Upgrade = 0x32,
        CancelUpgrade = 0x33,
        CancelAddon = 0x34,

        BuildingMorph = 0x35,
        Stim = 0x36,

        GameHashCheck = 0x37,
        StartGame = 0x3c,
        MapDownload = 0x3d,
        GameSlotModification = 0x3e,

        RaceChange = 0x41,
        SlotChange = 0x44,
        SwapPlayers = 0x45,
        InformationRequest = 0x49,
        PlayerDataTransfer = 0x4a,
        ForceNameTransfer = 0x4b,

        LobbyChat = 0x4c,
        BanPlayer = 0x4e,
        MapDataTransfer = 0x4f,
        MissionBriefingStart = 0x54,
        SetLatency = 0x55,
        ChangeReplaySpeed = 0x56,

        LeaveGame = 0x57,
        MinimapPing = 0x58,
        MergeDarkArchon = 0x5a,
        MakeGamePublic = 0x5b,
        GameChat = 0x5c,
        Terminate = 0xFF

    }

    public enum ObjectType
    {
        Marine = 0x00,
        Ghost = 0x01,
        Vulture = 0x02,
        Goloath = 0x03,
        GoliathTurret = 0x04,
        SiegeTank = 0x05,
        SiegeTankTurret = 0x06,
        SCV = 0x07,
        Wraith = 0x08,
        ScienceVessel = 0x09,
        GuiMontagFirebat = 0x0a,
        DropShip = 0x0b,
        Battlecruiser = 0x0c,
        SpiderMine = 0x0d,
        NuclearMissile = 0x0e,
 
        Civilian = 0x0f,
        SarahKarriganGhost = 0x10,
        AlanSchezarGoliath = 0x11,
        AlanSchezarTurret = 0x12,
        JimRaynorVulture = 0x13,
        JimRaynorMarine = 0x14,
        TomKazanskyWraith = 0x15,
        MagellanScienceVessel = 0x16,
        EdmundDukeTankMode = 0x17,
        EdmundDukeTurretTankMode = 0x18,
        EdmundDukeSiegeModel = 0x19,
        EdmundDukeTurretSiegeMode = 0x1a,
        ArcturusMengskBattlecruiser = 0x1b,
        HyperionBattlecruiser = 0x1c,
        NoradIIBattlecruiser = 0x1d,

        SiegeTankSiegeMode = 0x1e,
        SiegeTankTurretSiegeMode = 0x1f,
        Firebat = 0x20,
        ScannerSweep = 0x21,
        Medic = 0x22,
        
        Larva = 0x23,
        Egg = 0x24,
        Zergling = 0x25,
        Hydralisk = 0x26,
        Utralisk = 0x27,
        Broodling = 0x28,
        Drone = 0x29,
        Overlord = 0x2a,
        Mutalisk = 0x2b,
        Guardian = 0x2c,
        Queen = 0x2d,
        Defiler = 0x2e,
        Scourge = 0x2f,

        TorrasqueUltralisk = 0x30,
        MatriarchQueen = 0x31,
        InfestedTerran = 0x32,
        InfestedKerricanInfestedTerran = 0x33,
        UncleanOneDefiler = 0x34,
        HunterKillerHydralisk = 0x35,
        DevouringOneZergling = 0x36,
        KukulzaMutalisk = 0x37,
        KukulzaGuardian = 0x38,
        YggdrasillOverload = 0x39,
        Valkyrie = 0x3a,
        MutaliskCocoon = 0x3b,

        Corsair = 0x3c,
        DarkTemplar = 0x3d,
        Devourer = 0x3e,
        DarkArchon = 0x3f,
        Probe = 0x40,
        Zealot = 0x41,
        Dragoon = 0x42,
        HighTemplar = 0x43,
        Archon = 0x44,
        Shuttle = 0x45,
        Scout = 0x46,
        Arbiter = 0x47,
        Carrier = 0x48,
        Interceptor = 0x49,

        DarkTemplarHero = 0x4a,
        ZeratulDarkTemplar = 0x4b,
        TassadarZeratulArchon = 0x4c,
        FenixZealot = 0x4d,
        FenizDragoon = 0x4e,
        TassadarTemplar = 0x4f,
        MojoScout = 0x50,
        WarbringerReaver = 0x51,
        GantrithorCarrier = 0x52,
        Reaver = 0x53,
        Observer = 0x54,
        Scarab = 0x55,
        
        DanimothArbiter = 0x56,
        AldarisTemplar = 0x57,
        ArtanisScout = 0x58,

        RhynadonBadlandsCritter = 0x59,
        BengalaasJungleCritter = 0x5a,
        CargoShipUnused = 0x5b,
        MercenaryGunshipUnused = 0x5c,
        ScantidDesertCritter = 0x5d,
        KakaruTwillightCritter = 0x5e,
        RagnasaurAshworldCritter = 0x5f,
        UrsadonIceWorldCritter = 0x60,
        
        LurkerEgg = 0x61,
        RaszagalCorsair = 0x62,
        SamirDuranGhost = 0x63,
        AlexeiStukovGhost = 0x64,
        MapRevealer = 0x65,
        GerardDugalleBattlecruiser = 0x66,
        Lurker = 0x67,
        InfestedDuranInfestedTerran = 0x68,
        DisruptionWeb = 0x69,

        CommandCenter = 0x6a,
        ComsatStation = 0x6b,
        NuclearSilo = 0x6c,
        SupplyDepot = 0x6d,
        Refinery = 0x6e,
        Barracks = 0x6f,
        Academy = 0x70,
        Factory = 0x71,
        Starport = 0x72,
        ControlTower = 0x73,
        ScienceFacility = 0x74,
        CovertOps = 0x75,
        PhysicsLab = 0x76,

        StarbaseUnused = 0x77,
        MachineShop = 0x78,
        RepairBayUnused = 0x79,
        
        EngineeringBay = 0x7a,
        Armory = 0x7b,
        MissileTurret = 0x7c,
        Bunker = 0x7d,
        
        NoradIICrashed = 0x7e,
        IonCannon = 0x7f,
        UrajCrystal = 0x80,
        KhalisCrystal = 0x81,
        InfestedCommandCenter = 0x82,
        
        Hatchery = 0x83,
        Lair = 0x84,
        Hive = 0x85,
        NydusCanal = 0x86,
        HydraliskDen = 0x87,
        DefilerMound = 0x88,
        GreaterSpire = 0x89,
        QueensNest = 0x8a,
        EvolutionChamber = 0x8b,
        UltraliskCavern = 0x8c,
        Spire = 0x8d,
        SpawningPool = 0x8e,
        CreepColony = 0x8f,
        SporeColony = 0x90,
        UnusedZergBuilding_1 = 0x91,
        SunkenColony = 0x92,
        OvermindWithShell = 0x93,
        Overmind = 0x94,
        Extractor = 0x95,
        MatureChrysalis = 0x96,
        Cerebrate = 0x97,
        CerebrateDaggoth = 0x98,
        UnusedZergBuilding_2 = 0x99,
        
        Nexus = 0x9a,
        RoboticsFacility = 0x9b,
        Pylon = 0x9c,
        Assimilator = 0x9d,
        UnusedProtossBuilding_1 = 0x9e,
        Observatory = 0x9f,
        Gateway = 0xa0,
        UnusedProtossBuilding_2 = 0xa1,
        PhotonCannon = 0xa2,
        CitadelOfAdun = 0xa3,
        CyberneticsCore = 0xa4,
        TemplarArchives = 0xa5,
        Forge = 0xa6,
        Stargate = 0xa7,
        StasisCellPrison = 0xa8,
        FleetBeacon = 0xa9,
        ArbiterTribunal = 0xaa,
        RoboticsSupportBay = 0xab,
        ShieldBattery = 0xac,
        
        KhaydarinCrystalFormation = 0xad,
        ProtossTemple = 0xae,
        XelnagaTemple = 0xaf,

        MineralFieldType_1 = 0xb0,
        MineralFieldType_2 = 0xb1,
        MineralFieldType_3 = 0xb2,
        
        CaveUnused = 0xb3,
        Cave = 0xb4,
        CantinaUnused = 0xb5,
        MiningPlatformUnused = 0xb6,
        IndependentCommandCenterUnused = 0xb7,
        IndependentStarportUnused = 0xb8,
        IndependentJumpPortUnused = 0xb9,
        
        RuinsUnused = 0xba,
        KhaydarinCrystalFormationUnused = 0xbb,
        VespeneGeyser = 0xbc,
        WarpGate = 0xbd,
        PsiDisrupter = 0xbe,
        ZergMarker = 0xbf,
        TerranMarker = 0xc0,
        ProtossMarker = 0xc1,
        ZergBeacon = 0xc2,
        TerranBeacon = 0xc3,
        ProtossBeacon = 0xc4,
        ZergFlagBeacon = 0xc5,
        TerranFlagBeacon = 0xc6,
        ProtossFlagBeacon = 0xc7,
        PowerGenerator = 0xc8,
        OvermindCocoon = 0xc9,
        DarkSwarm = 0xca,
        
        FloorMissileTrap = 0xcb,
        FloorHatchUnused = 0xcc,
        LeftUpperLevelDoor = 0xcd,
        RightUpperLevelDoor = 0xce,
        LeftPitDoor = 0xcf,
        RightPitDoor = 0xd0,
        FloorGunTrap = 0xd1,
        LeftWallMissileTrap = 0xd2,
        LeftWallFlameTrap = 0xd3,
        RightWallMissileTrap = 0xd4,
        RightWallFlameTrap = 0xd5,
        StartLocation = 0xd6,
        Flag = 0xd7,
        YoungChrysalis = 0xd8,
        PsyEmitter = 0xd9,
        DataDisc = 0xda,
        KhaydarinCrystal = 0xdb,
        MineralClusterType_1 = 0xdc,
        MineralClusterType_2 = 0xdd,
        VespeneGasOrbType_1 = 0xde,
        VespeneGasOrbType_2 = 0xdf,
        VespeneGasSacType_1 = 0xe0,
        VespeneGasSacType_2 = 0xe1,
        VespeneGasTankType_1 = 0xe2,
        VespeneGasTankType_2 = 0xe3,
        None = 0xe4
    }

    public enum QueueType
    {
        Instant = 0x00,
        ShiftQueue = 0x01
    }

    public enum OrderType
    {
        Die = 0x00,
        Stop = 0x01,
        Guard = 0x02,
        PlayerGuard = 0x03,
        TurretGuard = 0x04,
        BunkerGuard = 0x05,
        Move = 0x06,
        ReaverStop = 0x07,
        Attack  = 0x08,
        AttackConcealed = 0x09,
        AttackUnit = 0x0a,
        AttackFixedRange = 0x0b,
        AttackTile = 0x0c,
        Hover = 0x0d,
        AttackMove = 0x0e,
        InfestMine_1 = 0x0f,
        Nothing_1 = 0x10,
        Powerup_1 = 0x11,
        TowerGuard = 0x12,
        TowerAttack = 0x13,
        VultureMine = 0x14,
        StayInRange = 0x15,
        TurretAttack = 0x16,
        Nothing_2 = 0x17,
        Nothing_3 = 0x18,
        DroneStartBuild = 0x19,
        DroneBuild = 0x1a,
        InfestMine_2 = 0x1b,
        InfestMine_3 = 0x1c,
        InfestMine_4 = 0x1d,
        BuildTerran = 0x1e,
        BuildProtoss_1 = 0x1f,
        BuildProtoss_2 = 0x20,
        ConstructingBuilding = 0x21,
        Repair = 0x22,
        RepairConcealed = 0x23,
        PlaceAddon = 0x24,
        BuildAddon = 0x25,
        Train = 0x26,
        RallyPointUnit = 0x27,
        RallyPointLocation = 0x28,
        ZergBirth = 0x29,
        MorphUnit = 0x2a,
        MorphBuilding = 0x2b,
        BuildSelfTerran = 0x2c,
        ZergBuildSelf = 0x2d,
        PlaceNydusCanalExit = 0x2e,
        EnterNydusCanal = 0x2f,
        BuildSelfProtoss = 0x30,
        Follow = 0x31,
        CarrierIdle = 0x32,
        CarrierMove = 0x33,
        CarrierStop = 0x34,
        CarrierAttackMove = 0x35,
        CarrierAttackConcealed = 0x36,
        CarrierMove_2 = 0x37,
        CarrierAttackUnit = 0x38,
        CarrierHoldPosition = 0x39,
        Reaver = 0x3a,
        ReaverAttackMove = 0x3b,
        ReaverAttackConcealed = 0x3c,
        ReaverAttackUnit = 0x3d,
        ReaverHoldPosition = 0x3e,
        TrainSubunit = 0x3f,
        InterceptorAttackMove = 0x40,
        ScarabAttackMove = 0x41,
        RechargeShieldsUnit = 0x42,
        RechargeShieldsCast = 0x43,
        ShieldBattery = 0x44,
        InterceptorReturn = 0x45,
        DroneLand = 0x46,
        LandBuilding = 0x47,
        LiftoffBuilding = 0x48,
        DroneLiftoff = 0x49,
        Liftoff = 0x4a,
        ResearchTech = 0x4b,
        Upgrade = 0x4c,
        LarvaIdle = 0x4d,
        SpawningLarva = 0x4e,
        HarvestMinerals = 0x4f,
        HarvestMineralsConcealed = 0x50,
        HarvestGas = 0x51,
        HarvestGasCheck = 0x52,
        HarvestGasEnterExit = 0x53,
        HarvestGasReturn = 0x54,
        HarvestMineralsMove = 0x55,
        HarvestMineralsCheck = 0x56,
        HarvestMineralsHarvesting = 0x57,
        HarvestMineralsInterrupted = 0x58,
        HarvestMineralsUnknown = 0x59,
        HarvestMineralsReturn = 0x5a,
        HarvestMineralsRecharge = 0x5b,
        EnterTransport = 0x5c,
        Pickup_1 = 0x5d,
        Pickup_2 = 0x5e,
        Pickup_3 = 0x5f,
        Pickup_4 = 0x60,
        Powerup_2 = 0x61,
        SiegeMode = 0x62,
        TankMode = 0x63,
        WatchTarget = 0x64,
        InitCreepGrowth = 0x65,
        SpreadCreep = 0x66,
        StoppingCreepGrowth = 0x67,
        GuardianAspect = 0x68,
        WarpingArchon = 0x69,
        CompletingArchonSummon = 0x6a,
        HoldPosition_2 = 0x6b,
        HoldPosition_3 = 0x6c,
        Cloak = 0x6d,
        Decloak = 0x6e,
        Unload = 0x6f,
        MoveUnload = 0x70,
        YamotoGun = 0x71,
        YamotoGunConcealed = 0x72,
        Lockdown = 0x73,
        Burrow = 0x74,
        BurrowIdle = 0x75,
        Unburrow = 0x76,
        DarkSwarm = 0x77,
        Parasite = 0x78,
        SpawnBroodlings = 0x79,
        EmpShockwave = 0x7a,
        NukeWait = 0x7b,
        NukeTrain = 0x7c,
        NukeLaunch = 0x7d,
        NukePaint = 0x7e,
        NukeUnit = 0x7f,
        NukeGround = 0x80,
        NukeTrack = 0x81,
        InitArbiter = 0x82,
        CloakNearbyUnits = 0x83,
        PlaceMine = 0x84,
        RightClickAction = 0x85,
        SuicideAttackUnit = 0x86,
        SuicideAttackLocation = 0x87,
        SuicideHoldPosition = 0x88,
        Recall = 0x89,
        RecallToLocation = 0x8a,
        ScannerSweep = 0x8b,
        ScannerIdle = 0x8c,
        DefensiveMatrix = 0x8d,
        PsiStorm = 0x8e,
        Irradiate = 0x8f,
        Plague = 0x90,
        Consume = 0x91,
        Ensnare = 0x92,
        StasisField = 0x93,
        Hallucination = 0x94,
        HallucinationKill = 0x95,
        ResetCollisionUnits = 0x96,
        ResetCollisionMine = 0x97,
        Patrol = 0x98,
        CtfCopInit = 0x99,
        CtfCopIdle = 0x9a,
        CtfCopReset = 0x9b,
        ComputerAi = 0x9c,
        AttackMoveEp = 0x9d,
        HarassMove = 0x9e,
        AiPatrol = 0x9f,
        GuardPost = 0xa0,
        RescuePassive = 0xa1,
        Neutral = 0xa2,
        ComputerReturn = 0xa3,
        InitPsiProvider = 0xa4,
        SelfDestructing = 0xa5,
        Critter = 0xa6,
        HiddenGun = 0xa7,
        OpenDoor = 0xa8,
        CloseDoor = 0xa9,
        HideTrap = 0xaa,
        RevealTrap = 0xab,
        EnableDoodad = 0xac,
        DisableDoodad = 0xad,
        WarpIn = 0xae,
        MedicIdle = 0xaf,
        Heal = 0xb0,
        MedicHealMove = 0xb1,
        MedicHoldPosition = 0xb2,
        MedicHealIdle = 0xb3,
        Restoration = 0xb4,
        DisruptionWeb = 0xb5,
        MindControl = 0xb6,
        WarpingDarkArchon = 0xb7,
        Feedback = 0xb8,
        OpticalFlare = 0xb9,
        Maelstrom = 0xba,
        JunkYardDog = 0xbc,
        Fatal = 0xb3
    }

    public enum UpgradeType
    {
        InfantryArmour = 0x00,
        VehiclePlating = 0x01,
        ShipPlating = 0x02,
        Carapace = 0x03,
        FlyerCarapace = 0x04,
        GroundArmour = 0x05,
        AirArmour = 0x06,
        InfantryWeapons = 0x07,
        VehicleWeapons = 0x08,
        ShipWeapons = 0x09,
        MeleeAttacks = 0x0a,
        MissileAttacks = 0x0b,
        FlyerAttacks = 0x0c,
        GroundWeapons = 0x0d,
        AirWeapons = 0x0e,
        PlasmaShields = 0x0f,
        
        U238Shells = 0x10,
        IonThrusters = 0x11,
        TitanReactor = 0x13,
        OcularImplants = 0x14,
        MoebiusReactor = 0x15,
        ApolloReactor = 0x16,
        ColossusReactor = 0x17,
        VentralSacs = 0x18,
        Antennae = 0x19,
        PneumatizedCarapace = 0x1a,
        MetabolicBoost = 0x1b,
        AndrenalGlands = 0x1c,
        MuscularAugments = 0x1d,
        GroovedSpines = 0x1e,
        GameteMeiosis = 0x1f,
        DefilerEnergy = 0x20,
        SingularityCharge = 0x21,
        LegEnhancement = 0x22,
        ScarabDamage = 0x23,
        ReaverCapacity = 0x24,
        GraviticDrive = 0x25,
        SensorArray = 0x26,
        GraviticBooster = 0x27,
        KhaydaringAmulet = 0x28,
        ApialSensors = 0x29,
        GraviticThrusters = 0x2a,
        CarrierCapacity = 0x2b,
        KhaydarinCore = 0x2c,
        ArgusJewel = 0x2f,
        ArgusTalisman = 0x31,
        CaduceusReactor = 0x33,
        ChitinousPlating = 0x34,
        AnabolicSynthesis = 0x35,
        CharonBoosters = 0x36
    }

    public enum TechType
    {
        StimPack = 0x00,
        Lockdown = 0x01,
        EmpShockwave = 0x02,
        SpiderMines = 0x03,
        SiegeTank = 0x05,
        Irradiate = 0x07,
        YamatoGun = 0x08,
        CleakingField = 0x09,
        PersonalCloaking = 0x0a,
        Burrow = 0x0b,
        SpawnBroodlings = 0x0d,
        Plague = 0x0f,
        Consume = 0x10,
        Ensnare = 0x11,
        PsionicStorm = 0x13,
        Hallucination = 0x14,
        Recall = 0x15,
        StasisField = 0x16,
        Restoration = 0x18,
        DisruptionWeb = 0x19,
        MindControl = 0x1b,
        OpticalFlare = 0x1e,
        Maelstrom = 0x1f,
        LurkerAspect = 0x20
    }

    public enum LeaveGameType
    {
        Quit = 0x01,
        Dropped = 0x06
    }

    public enum HotKeyActionType
    {
        Save = 0x00,
        Recall = 0x01,
        Unknown = 0x02
    }

}
